services:
  app:
    build: 
      context: .
      target: production
    container_name: bws-bali-penida-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src/storage:/var/www/html/storage
      - ./src/bootstrap/cache:/var/www/html/bootstrap/cache
      - ./docker/logs:/var/log
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL:-http://localhost}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    depends_on:
      - redis
    networks:
      - bws-network

  redis:
    image: redis:7-alpine
    container_name: bws-bali-penida-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bws-network

volumes:
  redis_data:

networks:
  bws-network:
    driver: bridge